### ISSUE TITLE
Misleading env protection setting

### ISSUE THREAD

**Issue by caadar** [zaufi/paludis-hooks#18]
My /etc/env.d/90cave overwritten and all chages lost.

You set CONFIG_PROTECT='/etc/env.d/90cave' but /etc.d already in `CONFIG_PROTECT_MASK' by Gentoo profile that makes it useless as any directory which is listed in CONFIG_PROTECT (and any subdirectories thereof), except for any which are listed in CONFIG_PROTECT_MASK (and subdirectories) are automatically 'protected' by Portage when copying an image from DESTDIR to ROOT -- https://devmanual.gentoo.org/general-concepts/config-protect/index.html (it seems correct for Paludis also).

Am I wrong? How do you protect env options from automatic merge?

**Comment by zaufi** [comment]
Lets check the `/usr/portage/profiles`:
    root@gentop〉/usr/portage/profiles〉timestamp: 2016/06/09 02:30〉grep -nir "CONFIG_PROTECT" *
    base/make.defaults:25:CONFIG_PROTECT="/etc"
    base/make.defaults:26:CONFIG_PROTECT_MASK="/etc/env.d /etc/gconf"
    info_vars:11:CONFIG_PROTECT
    info_vars:12:CONFIG_PROTECT_MASK

I see `/etc` is protected, except `/etc/env.d`... I have my [`/etc/env.d/90cave`](https://github.com/zaufi/etc-files/blob/hardware/notebook/MSI-GP60-2PE-Leopard/env.d/90cave) little bit different than one installed by `paludis-hooks`. And yes, I have `/etc` files I've changed in a git repo... Being **unprotected**, I've tired to rollback to my version all the time after `paludis-hooks` gets installed, so I've add a `CONFIG_PROTECT` for this file...

Heh, maybe it was a bad idea to do it in the package... I still can have what I wan't w/o this option in the shipped `90cave`...

**Comment by caadar** [comment]
OK, I see.

May be drop some notes in shipped /etc/env.d/90cave?

**Comment by caadar** [comment]
OK, I see.

May be drop some notes in shipped /etc/env.d/90cave?

**Comment by caadar** [comment]
OK, I see.

May be drop some notes in shipped /etc/env.d/90cave?

**Comment by caadar** [comment]
OK, I see.

May be drop some notes in shipped /etc/env.d/90cave?

**Comment by caadar** [comment]
OK, I see.

May be drop some notes in shipped /etc/env.d/90cave?
