### ISSUE TITLE
print-ebuild-path installation seems broken

### ISSUE THREAD

**Issue by caadar** [zaufi/paludis-hooks#19]
`````
 * Installing hooks into paludis configuration dir...
find: '/var/tmp/paludis/app-paludis-paludis-hooks-scm/image//usr/libexec/cave/commands/print-ebuild-path':
 No such file or directory
`````

**Comment by zaufi** [comment]
Please tell me the output of `cave show paludis-hooks`

**Comment by caadar** [comment]
[paludis-hooks.log](https://github.com/zaufi/paludis-hooks/files/2089104/paludis-hooks.log)

**Comment by zaufi** [comment]
Please use the fresh [ebuild](https://github.com/zaufi/zaufi-overlay/blob/master/sys-apps/paludis-hooks/paludis-hooks-scm.ebuild), I've just updated it to fix the typo on install
