### ISSUE TITLE
setup_pkg_env.bash might print to standard output 

### ISSUE THREAD

**Issue by hasufell** [zaufi/paludis-hooks#3]
https://github.com/zaufi/paludis-hooks/blob/master/package.env/setup_pkg_env.bash.in#L57

I don't know about the possible side effects of this, but the [bashrc docs](http://paludis.exherbo.org/configuration/bashrc.html) say:
```
This file must not be used to output anything to standard output.
```

**Comment by zaufi** [comment]
Done! Thanks for note.
