### ISSUE TITLE
cave resolve --ask

### ISSUE THREAD

**Issue by hasufell** [zaufi/paludis-hooks#5]
Just wanted your opinion on [this bash function/alias](https://gist.github.com/hasufell/dccd0ce21ec1803cb888). I think it is a common "wtf" moment for people who switch to paludis when they don't find the `--ask` switch.

Specifying a resume file and resuming manually are two commands (even if you have aliases for both) while with --ask it is just one step and probably more intuitive for most users.

I currently see two problems with this script:
- it does not check if it overwrites a previous resume file and I'm not sure it even should
- it doesn't allow to pass parameters to `cave resume`

**Comment by zaufi** [comment]
Personally I don't want to use smth like this... yeah, first time, when I didn't know `paludis` well, I wanted the `--ask` feature… but later I've realized a power of resume file(s), so I don't need `--ask` any more. Moreover, I consider this option as harmful:
* it make people lazy -- finding replacement for `--ask` they could stuck on it and stop moving forward reading about better replacement…
* sometimes I use more than one resume file simultaneously :-)
* as for me inability to pass options to `resume` is a real lack, cuz `--skip-phase` and/or `--change-phases-for` helped me many times
* and finally, personally I, don't like idea to have resume file in a home directory -- depending on ways how do you call that function it'll use/leave this file in different homes (your user or `root` user)...

as you probably may see, I use pretty short alias for both phases: `crz` for _resolve with "default" resume file_ and `cz` for _resume from "default" resume file_… to observe results of `resolve` I just scroll my terminal window and type `cz` if everything is ok -- that is not a really hard for me :)
